# Generated by Django 4.2.6 on 2024-02-05 11:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Область')),
                ('region_slug', models.SlugField(max_length=70, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Області',
            },
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=12, unique=True, verbose_name='Тур / стадія плей-оф')),
            ],
            options={
                'verbose_name': 'Раунд',
                'verbose_name_plural': 'Раунди',
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва турніру')),
                ('full_name', models.CharField(max_length=350, verbose_name='Повна назва турніру')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('link', models.URLField(blank=True, verbose_name='посилання на офіційний сайт')),
                ('logotype', models.ImageField(blank=True, default='footballs/static/footballs/img/logo_teams/Снимок.PNG', upload_to='footballs/static/footballs/img/logo_tournaments/', verbose_name='Логотип')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='footballs.regions', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Турнір',
                'verbose_name_plural': 'Турніри',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=80, verbose_name='Назва команди')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Повна назва')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=350, verbose_name='Адреса клубу/команди')),
                ('link', models.URLField(blank=True, verbose_name='посилання на офіційний сайт')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('logotype', models.ImageField(blank=True, null=True, upload_to='footballs/static/footballs/img/logo_teams/', verbose_name='Логотип')),
                ('born', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1940)], verbose_name='Рік заснування')),
                ('stadium', models.CharField(blank=True, max_length=50, verbose_name='Домашній стадіон')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='footballs.regions', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
            },
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10, verbose_name='Сезон')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footballs.regions', verbose_name='Область')),
                ('team', models.ManyToManyField(related_name='standings', to='footballs.teams', verbose_name='Команди')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footballs.tournaments', verbose_name='Назва турніру')),
            ],
            options={
                'verbose_name': 'Турнірна таблиця сезону',
                'verbose_name_plural': 'Турнірні таблиці сезону',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_event', models.DateTimeField(blank=True, verbose_name='Дата')),
                ('goals_team1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Забити голи - господарі')),
                ('goals_team2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Забити голи - гості')),
                ('status', models.CharField(blank=True, choices=[('not_played', 'Не зіграно'), ('played', 'Зіграно'), ('tech_defeat', 'Тех. поразка')], default='not_played', max_length=11, verbose_name='Статус')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour', to='footballs.rounds', verbose_name='Тур')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams1', to='footballs.teams', verbose_name='Команда господар')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams2', to='footballs.teams', verbose_name='Команда гостей')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches', to='footballs.standings', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Матчі',
                'verbose_name_plural': 'Матчі',
            },
        ),
    ]
