# Generated by Django 4.2.6 on 2023-12-13 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('association', models.CharField(max_length=20, unique=True, verbose_name='Організація')),
                ('association_full_name', models.CharField(blank=True, max_length=100, verbose_name='Повна назва організації')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='Територіальна громада')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('emblem', models.ImageField(blank=True, default='footballs/static/footballs/img/logo_teams/Снимок.PNG', upload_to='footballs/static/footballs/img/logo_association/', verbose_name='Логотип')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Асоціація',
                'verbose_name_plural': 'Асоціації',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Область')),
                ('region_slug', models.SlugField(max_length=70, unique=True, verbose_name='Slug')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Області',
            },
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=12, unique=True, verbose_name='Тур / стадія плей-оф')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('team', models.CharField(max_length=80, verbose_name='Назва команди')),
                ('team_full_name', models.CharField(blank=True, max_length=200, verbose_name='Повна назва')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=350, verbose_name='Адреса клубу/команди')),
                ('link', models.URLField(blank=True, verbose_name='посилання на офіційний сайт')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('logotype', models.ImageField(blank=True, null=True, upload_to='footballs/static/footballs/img/logo_teams/', verbose_name='Логотип')),
                ('born', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1940)], verbose_name='Рік заснування')),
                ('stadium', models.CharField(blank=True, max_length=50, verbose_name='Домашній стадіон')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='footballs.regions', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва турніру')),
                ('full_name', models.CharField(max_length=350, verbose_name='Повна назва турніру')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('link', models.URLField(blank=True, verbose_name='посилання на офіційний сайт')),
                ('logotype', models.ImageField(blank=True, default='footballs/static/footballs/img/logo_teams/Снимок.PNG', upload_to='footballs/static/footballs/img/logo_tournaments/', verbose_name='Логотип')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('association_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='footballs.associations', verbose_name='Огранізація проведення')),
            ],
            options={
                'verbose_name': 'Турнір',
                'verbose_name_plural': 'Турніри',
            },
        ),
        migrations.CreateModel(
            name='TournamentTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10, verbose_name='Сезон')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footballs.regions', verbose_name='Область')),
                ('team_id', models.ManyToManyField(related_name='teams', to='footballs.teams', verbose_name='Команди')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footballs.tournaments', verbose_name='Назва турніру')),
            ],
            options={
                'verbose_name': 'Турнірна таблиця сезону',
                'verbose_name_plural': 'Турнірні таблиці сезону',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(blank=True, default='01.01.2023', verbose_name='Дата')),
                ('match_time', models.TimeField(blank=True, default='00:00', verbose_name='Час')),
                ('host_team_goals', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Забити голи - господарі')),
                ('visiting_team_goals', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Забити голи - гості')),
                ('status', models.CharField(blank=True, choices=[('not_played', 'Не зіграно'), ('played', 'Зіграно'), ('tech_defeat', 'Тех. поразка')], default='not_played', max_length=11, verbose_name='Статус')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('host_team_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_home', to='footballs.teams', verbose_name='Команда господар')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tur', to='footballs.rounds', verbose_name='Тур')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournaments', to='footballs.tournaments', verbose_name='Турнір')),
                ('visiting_team_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_guests', to='footballs.teams', verbose_name='Команда гостей')),
            ],
            options={
                'verbose_name': 'Матчі',
                'verbose_name_plural': 'Матчі',
            },
        ),
        migrations.AddField(
            model_name='associations',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='footballs.regions', verbose_name='Область'),
        ),
    ]
