# Generated by Django 4.2.6 on 2024-02-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='into_table',
            field=models.BooleanField(default=True, verbose_name='Play_off'),
        ),
        migrations.AddField(
            model_name='standings',
            name='print_standing',
            field=models.BooleanField(default=True, verbose_name='Вивід турн. табл'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='round',
            field=models.CharField(max_length=20, unique=True, verbose_name='Тур / стадія плей-оф'),
        ),
    ]
