# Generated by Django 4.2.6 on 2024-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballs', '0002_rounds_into_table_standings_print_standing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standings',
            name='print_standing',
            field=models.BooleanField(default=True, verbose_name='Турнірна тааблиця'),
        ),
    ]
